print("Getting to know you!")
print()
yourName = input("What's your name?: ")
yourFood = input("What's your favorite food?: ")
yourMusic = input("What's your favorite music?: ")
yourHome = input("Where do you live?: ")
print()
print("You are")
print(yourName)
print("You're probably hungry for")
print(yourFood)
print("and you're definitely getting your groove on to")
print(yourMusic)
print("living in the amazing")
print(yourHome)
print()
print("Have a great day!")